// This file is auto-generated by @hey-api/openapi-ts

export type AiRecommendation = {
  lineNum: number;
  text: string;
  rationale: string;
};

export type DocumentResponse = {
  id: string;
  fileName: string;
  s3Key: string;
  signedUrl: string;
};

export type JobDescriptionRequest = {
  id: string;
  jobDescription: string;
};

export type ProcessRecommendationsRequest = {
  id: string;
  recommendations: Array<RecommendationToProcess>;
};

export type RecommendationToProcess = {
  text: string;
  lineNum: number;
};

export type ResumeAiResponse = {
  recommendations: Array<AiRecommendation>;
};

export type PostResumesData = {
  body?: {
    file: Blob | File;
  };
  path?: never;
  query?: never;
  url: "/resumes";
};

export type PostResumesResponses = {
  /**
   * OK
   */
  200: DocumentResponse;
};

export type PostResumesResponse =
  PostResumesResponses[keyof PostResumesResponses];

export type GetResumesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/resumes/{id}";
};

export type GetResumesByIdResponses = {
  /**
   * OK
   */
  200: DocumentResponse;
};

export type GetResumesByIdResponse =
  GetResumesByIdResponses[keyof GetResumesByIdResponses];

export type PostResumesRecommendData = {
  body: JobDescriptionRequest;
  path?: never;
  query?: never;
  url: "/resumes/recommend";
};

export type PostResumesRecommendResponses = {
  /**
   * OK
   */
  200: ResumeAiResponse;
};

export type PostResumesRecommendResponse =
  PostResumesRecommendResponses[keyof PostResumesRecommendResponses];

export type PostResumesProcessRecommendationsData = {
  body: ProcessRecommendationsRequest;
  path?: never;
  query?: never;
  url: "/resumes/processRecommendations";
};

export type PostResumesProcessRecommendationsResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostResumesProcessRecommendationsResponse =
  PostResumesProcessRecommendationsResponses[keyof PostResumesProcessRecommendationsResponses];

export type GetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type GetResponses = {
  /**
   * OK
   */
  200: string;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type ClientOptions = {
  baseUrl: "http://localhost:5185" | (string & {});
};
