// This file is auto-generated by @hey-api/openapi-ts

export type PostResumesData = {
  body?: {
    file: Blob | File;
  };
  path?: never;
  query?: never;
  url: "/resumes";
};

export type PostResumesResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetResumesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/resumes/{id}";
};

export type GetResumesByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type GetResponses = {
  /**
   * OK
   */
  200: string;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type ClientOptions = {
  baseUrl: "http://localhost:5185" | (string & {});
};
