// This file is auto-generated by @hey-api/openapi-ts

export type AiRecommendation = {
  lineNum: number;
  text: string | null;
  rationale: string | null;
};

export type JobDescriptionRequest = {
  id?: string;
  jobDescription: string | null;
};

export type ResumeAiResponse = {
  recommendations: Array<AiRecommendation> | null;
};

export type UploadResumeResponse = {
  id?: string;
};

export type PostResumesData = {
  body?: {
    file: Blob | File;
  };
  path?: never;
  query?: never;
  url: "/resumes";
};

export type PostResumesResponses = {
  /**
   * OK
   */
  200: UploadResumeResponse;
};

export type PostResumesResponse =
  PostResumesResponses[keyof PostResumesResponses];

export type PostResumesRecommendData = {
  body: JobDescriptionRequest;
  path?: never;
  query?: never;
  url: "/resumes/recommend";
};

export type PostResumesRecommendResponses = {
  /**
   * OK
   */
  200: ResumeAiResponse;
};

export type PostResumesRecommendResponse =
  PostResumesRecommendResponses[keyof PostResumesRecommendResponses];

export type GetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type GetResponses = {
  /**
   * OK
   */
  200: string;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type ClientOptions = {
  baseUrl: "http://localhost:5185" | (string & {});
};
